### ISSUE TITLE
请求添加幻灯片播放的功能

### ISSUE THREAD

**Issue by Drlong10th** [hospotho/Image-Viewer#1]
点一个键能以固定间隔播放所有照片的那种，谢谢

**Comment by hospotho** [comment]
這功能確實有用，完全忘了加。等我和custom element和shadow dom搏鬥完，下版本1.36就加進來
有希望是直接加keyboard shortcut還是control panel加一個按鍵？

**Comment by Drlong10th** [comment]
这两种办法都可以啊，我是没什么偏好啦。谢谢大大

**Comment by hospotho** [comment]
1.36已更新，相關commit:
cf8a305739181749ead68699bb076e8dac077350 1cd2e8726e199135a5be274bbe37f572e3d911f4 c2a6d72ef0b47d7e7a07fdc4964c45c1568b9046 ccd4285c726a3e7663d26e3f1e2a8d5e30746f1d
